name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*' # Push events to every tag

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      # Checkout the current tag
      - uses: actions/checkout@v2 
        with:
          ref: ${{github.ref}}
          # Put the checked out files inside a dedicated folder
          path: ${{github.ref_name}}
          clean: false
      # Delete the .git folder
      - run: rm -rf ${{github.ref_name}}/.git   
      # Deploy the folder to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './${{github.ref_name}}'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'             